config/routes.rb
Rails.application.routes.draw do

  root 'static#splash'
  get 'home' => "home#index"
  get 'about' => 'static#about'
  get 'resources' => 'static#resources'

  get 'external_link_warning' => 'static#external_link_warning'
  get 'content/:page' => 'static#content'
  get 'content/' => 'static#content'

  get 'privacy_policy_document' => 'static#content', :page => "privacy_policy"
  get 'terms_of_service' => 'static#content', :page => "terms_of_service"

  match 'research_topics_tab', to: "research_topics#research_topics", via: :get, as: :research_topics_ajax
  get 'vote_counter' => 'research_topics#vote_counter'
  match 'comment_on_research_topic', to: "research_topics#comment", via: [:post], as: :comment_on_research_topic
  resources :research_topics

  get 'research_surveys' => 'research#research_surveys', as: :surveys

  get 'research' => 'research#index'
  get 'research_prioritization' => 'research#index'
  get 'research_active_studies' => 'research#active_studies'
  get 'research_completed_research' => 'research#completed_research'
  get 'research_my_contributions' => 'research#my_contributions'

  get 'data_connections' => 'research#data_connections'

  get 'research_surveys/report/:answer_session_id', to: 'surveys#show_report', as: :survey_report
  get 'research_surveys/:question_flow_id', to: 'surveys#start_survey', as: :start_survey
  get 'research_surveys/:answer_session_id/:question_id', to: 'surveys#ask_question', as: :ask_question
  match 'research_surveys/process_answer', to: 'surveys#process_answer', via: :post, as: :process_answer
  get 'questions/frequencies(/:question_id/:answer_session_id)', to: "questions#frequencies", as: :question_frequencies, format: :json
  get 'questions/typeahead/:question_id', to: "questions#typeahead", as: :question_typeahead, format: :json

  get 'health_data' => 'health_data#index'
  get 'health_data/my_trends' => 'health_data#index', as: :my_trends
  get 'health_data/my_health_measures' => 'health_data#my_health_measures', as: :my_health_measures
  get 'health_data/my_dashboard' =>  'health_data#my_dashboard', as: :my_dashboard
  get 'health_data/my_connections' =>  'health_data#my_connections', as: :my_connections

  get 'data_reports' => 'health_data#reports'
  get 'data_medications' => 'health_data#medications'
  get 'data_intro' => 'health_data#intro'
  match 'check_in', to: "health_data#check_in", via: :post, as: :check_in

  match 'members', to: 'members#index', via: :get, as: 'members' # show
  match 'members/profile', to: 'members#profile', as: 'social_profile', via: :get #edit
  match 'members/profile', to: 'members#update_profile', as: 'update_social_profile', via: [:put, :post, :patch] # update
  match 'locations', via: :get, as: :locations, format: :json, to: 'members#locations'

  get 'blog' => 'blog#blog'
  get 'blog_findings' => 'blog#blog_findings'

  get 'account' => 'account#account'
  get 'account_export' => 'account#account_export'
  match 'consent', to: "account#consent", as: :consent, via: [:get, :post]
  match 'privacy_policy', to: "account#privacy_policy", as: :privacy, via: [:get, :post]
  match 'update_account', to: 'account#update', as: 'update_account', via: :patch
  match 'change_password', to: 'account#change_password', as: 'change_password', via: :patch

  match 'members/discussion/terms_and_conditions', to: 'account#terms_and_conditions', via: :get, as: :terms_and_conditions

  get 'admin' => 'admin#users'
  match 'admin/users', to: 'admin#users', as: 'admin_users', via: [:get, :post]
  get 'admin/surveys' => 'admin#surveys', as: 'admin_surveys'
  get 'admin/blog' => 'admin#blog', as: 'admin_blog'
  get 'admin/notifications' => 'admin#notifications', as: 'admin_notifications'
  get 'admin/research_topics' => 'admin#research_topics', as: 'admin_research_topics'
  get 'admin/research_topic/:id' => 'admin#research_topic', as: 'admin_research_topic'

  match 'add_role', to: "admin#add_role_to_user", via: :post, as: :add_role, format: :js
  match 'remove_role', to: "admin#remove_role_from_user", via: :post, as: :remove_role, format: :js
  match 'destroy_user', to: "admin#destroy_user", via: :post, as: :destroy_user, format: :js

  get 'pprn' => 'application#toggle_pprn_cookie'

  resources :questions
  match 'vote', to: 'votes#vote', via: :post, as: :vote
  match 'vote', to: 'research_topics#index', via: :get, as: :vote_fake

  resources :posts, except: [:show, :index]

  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions'}

  devise_scope :user do
    get 'pairing_wizard' => 'registrations#pairing_wizard'
    post 'pairing_wizard' => 'registrations#pairing_wizard' #enables trying specified email
    get 'redirect_to_lcp_reg' => 'registrations#redirect_to_lcp_reg'
  end

  mount Forem::Engine, :at => '/members/discussion'

end

app/controllers/health_data_controller.rb
class HealthDataController < ApplicationController
  before_action :authenticate_user!, :only => [:data_explore, :data_reports, :medications]
  before_action :set_active_top_nav_link_to_health_data
  before_action :validate_oodt_module, :only => [:explore, :reports]
  before_action :validate_validic_module, :only => []
  before_action :check_in_setup

  layout "health_data"

  def validate_oodt_module
    raise "OODT must be enabled for this feature." if !OODT_ENABLED
  end

  def validate_validic_module
    raise "Validic must be enabled for this feature." if !Figaro.env.validic_enabled
  end

  def my_dashboard
    @med_list = (current_user and OODT_ENABLED) ? current_user.get_med_list : {}
  end

  def my_health_measures
    @chart_urls = (current_user and OODT_ENABLED) ? current_user.get_chart_urls : {}
  end


  def submit_check_in
    params[:question_id]
    params[:value]
  end

  def check_in
    question = Question.find(params[:question_id])

    @answer = @answer_session.process_answer(question, params)

    render json: {answer: @answer, next_question_id: (@answer.next_question.id if @answer and @answer.next_question)}
  end


  private

  def check_in_setup
    if current_user
      @question_flow = QuestionFlow.find_by_name_en("Daily Trends")
      @answer_session = AnswerSession.most_recent(@question_flow.id, current_user.id)

      if @answer_session.nil? or (@answer_session.completed? and (Time.zone.now - @answer_session.updated_at) >= Figaro.env.check_in_frequency.to_i * 3600) or params[:new_check_in]
        #raise StandardError
        @answer_session = AnswerSession.create(user_id: current_user.id, question_flow_id: @question_flow.id)
      end
    end

  end


end

app/views/health_data/_data_source_table.html.haml
-# Load dummy health data for demonstration
- dummy_health_data = YAML.load_file("config/health_data.yml")
- dummy_data_sources = dummy_health_data["data_sources"]
- dummy_data_source_types = dummy_health_data["data_source_types"]


%table.table.table-striped
  %thead
    %td
    - dummy_data_source_types.each do |data_source_type|
      %td= data_source_type.to_s.titleize
  - dummy_data_sources.each do |data_source_name,supported_data_source_types|
    %tr
      %td= data_source_name
      - dummy_data_source_types.each do |data_source_type|
        %td
          - if supported_data_source_types.include?(data_source_type)
            %i.fa.fa-times

app/views/health_data/_health_check_in.html.haml
-#= render partial: "health_check_in_helper", :locals => { question: "How are you feeling today?", last_updated_at: "7 days ago", first_question: true,
-#                                               answer_type: :slider, answer_options: ["Horrible", "Amazing"]}



-##accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
-#  .panel.panel-default
-#    #headingOne.panel-heading{:role => "tab"}
-#      %h4.panel-title
-#        %a{"aria-controls" => "collapseOne", "aria-expanded" => "true", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne"}
-#          See all other states of this "health check in" survey

-#    #collapseOne.panel-collapse.collapse{"aria-labelledby" => "headingOne", :role => "tabpanel"}
-#      .panel-body


-#        = render partial: "health_check_in_helper", :locals => { question: "How would you describe your general well-being over the last week?", last_updated_at: "7 days ago",
-#                                                       answer_type: :options, answer_options: ["Generally Well", "Slightly Below Par", "Poor", "Very Poor", "Terrible"]}


-#        = render partial: "health_check_in_helper", :locals => { question: "On average, over the past week, would you rate your abdominal pain as:", last_updated_at: "7 days ago",
-#                                                       answer_type: :options, answer_options: ["None", "Mild", "Moderate","Severe"]}

-#        = render partial: "health_check_in_helper", :locals => { question: "On average, over the past week, how many liquid or very soft stools have you had per day", last_updated_at: "10 days ago",
-#                                                       answer_type: :text }


-#        .panel.panel-default
-#          .panel-body.text-center
-#            .alert.alert-success
-#              %p Thank you. You are all Checked in!
-#              %small= link_to "Back to Last Question"
-#              |
-#              %small= link_to "Do Health Check-in Again"

-#        .panel.panel-default
-#          .panel-body.text-right
-#            %small
-#              You've updated your health in the last 12 hours. Something change?
-#              = link_to "Do health check-in again."



%form#check-in{action: check_in_path}
  - @question_flow.all_questions.each do |question|
    = render partial: "health_check_in_helper", :locals => { question: question, answer_session: @answer_session, question_flow: @question_flow, current: (question == @answer_session.next_question) }
  #completion_message{class: ("hidden" unless @answer_session.completed?) }
    .panel.panel-default
      .panel-body.text-center
        .alert.alert-success
          %p Thank you. You are all Checked in!
          %small= link_to "Update my Health Again", health_data_path(new_check_in: true)



        -##accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
-#  .panel.panel-default
-#    #headingOne.panel-heading{:role => "tab"}
-#      %h4.panel-title
-#        %a{"aria-controls" => "collapseOne", "aria-expanded" => "true", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne"}
-#          See all other states of this "health check in" survey
-#
-#    #collapseOne.panel-collapse.collapse{"aria-labelledby" => "headingOne", :role => "tabpanel"}
-#      .panel-body
-#
-#        - @check_in_questions[1..@check_in_questions.size-1].each do |question|
-#          = render partial: "health_check_in_helper", :locals => { question: question}
-#

app/views/health_data/_health_check_in_helper.html.haml
- if question
  .panel.panel-default.question{data: {question_id: question.id}, class: ("hidden" unless current )}
    .panel-body
      .row
        .col-md-9
          %h4.text-primary
            = question.text
          - if question.answer_template.display_type.name == "range"
            %input{type: question.answer_template.display_type.input_type, name: "#{question.id}[#{question.answer_template.id}]", id: "question_#{question.id}_#{question.answer_template.id}", min: question.answer_template.min_value, max: question.answer_template.max_value}
            .pull-left.text-primary.small= question.answer_template.bottom_label
            .pull-right.text-primary.small= question.answer_template.top_label

          - elsif question.answer_template.display_type.name == "multiple_choice_buttons"
            %div{data: {toggle: "buttons"}}
              - question.answer_template.answer_options.each do |option|
                %label.btn.btn-primary
                  %input{type: question.answer_template.display_type.input_type, autocomplete: "off", value: option.value, name: "#{question.id}[#{question.answer_template.id}]", id: "question_#{question.id}_#{question.answer_template.id}"}
                  = option.value
          - elsif question.answer_templates
            .input-group.col-md-6
              %input.form-control{:type => "text"}
              %span.input-group-btn
                %button.btn.btn-primary.submit Submit

        .col-md-3.text-right
          %small.muted
            Last Updated
            = answer_session.updated_at.localtime.to_formatted_s(:short)
          %br/
          - unless question == answer_session.question_flow.first_question
            %small
              = link_to "Back to Last Question", "#", class: "prev-question", data: { prev_question_id: question.previous_question(question_flow).id }

app/views/health_data/_my_dashboard.html.haml
Dashboard goes here.
%br/

.panel.panel-default
  .panel-heading
    %h3.panel-title My Medications

  - if @med_list.empty?
    .panel-body
      .alert.alert-info We currently have no medication information on you.
  - elsif @med_list['meds'].any?
    %table.table
      %tbody
        - @med_list['meds'].each do |med|
          %tr
            %td= med


  .panel-footer
    %em.pull-left= "Current as of #{@med_list['date']}" if @med_list['date']
    - if current_user
      %a.btn.btn-success.pull-right{href: (current_user.get_med_update_url if ENV["oodt_enabled"])} Update my Meds
    .clearfix

app/views/health_data/_my_health_data.html.haml
- if current_user
  .panel.panel-default
    .list-group
      - current_user.incomplete_surveys.each do |survey|
        = link_to start_or_resume_survey(survey, survey.most_recent_answer_session(current_user)), class: 'list-group-item' do
          %h3
            = survey.name
            .btn.btn-success.btn-lg.pull-right
              Resume
              &nbsp;
              .fa.fa-arrow-right
            = render partial: 'surveys/partials/session_progress', locals: {stats: survey.completion_stats(current_user), question_flow: survey, answer: nil}
      - current_user.unstarted_surveys.each do |survey|
        = link_to start_or_resume_survey(survey), class: 'list-group-item' do
          %h3
            = survey.name
            .btn.btn-success.btn-lg.pull-right
              Start
              &nbsp;
              .fa.fa-arrow-right
          %p Survey not yet started.
          %p
            %strong
              Estimated time commitment:
              = survey.total_time.ceil
              minutes for
              = survey.all_questions.length
  -#
  -# link_to "Complete Survey", start_or_resume_survey(survey), class: "btn btn-success btn-sm"

  -#%td.no-wrap{:style => "background-color: #f5f5f5 !important;"}
  -#  Today
  -#%td{:style => "background-color: #f5f5f5 !important;"}
  -#  %div.col-md-4.col-xs-12.text-center
  -#    How are you feeling?
  -#    / %br/
  -#    / %i.fa.fa-circle
  -#    / &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  -#    / %i.fa.fa-circle
  -#    / &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  -#    / %i.fa.fa-circle
  -#    / &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  -#    / %i.fa.fa-circle
  -#    / %br/
  -#    %input{:type => "range"}
  -#    %br/
  -#  .col-md-6.col-xs-12
  -#    %textarea.form-control{:placeholder => "Type a journal entry here.."}
  -#    %br/
  -#  %div.col-md-2.col-xs-12
  -#    %a.btn.btn-primary.btn-block{:href=>"javascript:location.reload();"} Post

app/views/health_data/_my_reports.html.haml
- if current_user
  %h3 My Reports
  %hr/

  - current_user.health_attribute_data.each do |attribute|
    %h4= attribute[:title]
    / = render :partial => "shared/progress", locals: {attribute: attribute}

    .progress
      - attribute[:zones].each do |zone|
        .progress-bar.progress-bar-success{style: "width: #{zone[:endValue] / 10}%"}
          %span= zone[:title]



      /{element: 1, title: "Blood Type", value: 500, zones: [{startValue: 1, endValue: 888, title: "Low"}, {startValue: 300, endValue: 999, title: "High"}], markers: [{value: 1, title: "User Max"}, {value: 2, title: "User Average"}] },


    %hr/

app/views/health_data/_tutorial.html.haml
%h4 Welcome to the CCFA Partners PPRN My Health Data Environment

%p In this area you will be able to:
%ul
  %li Record, Track and Analyze your IBD Symptoms
  %li Link and Share Information from Selected Apps and Devices

%h4 How to participate

%p We have identified 2 ways to share data.  Sources of data include:
%ul
  %li Direct participation in CCFA Partners surveys (participant entered data (surveys & portal)
  %li Authorization of data to be shared from external sources

%p Apps and devices offer a growing range of ways to get the important health information you're tracking into you’re My Health Data record. Many apps let you analyze and managethat information to help you achieve your health goals.

%p Connected apps and devices are websites, software programs, and mobile apps that can help you get more out of—and put more into My Health Data.

%p My Health Data lets you integrate data from apps and devices with your survey data, to track your health, manage your goals, and simultaneously contribute to research.


%h4 Apps & Devices

%p Share your data from the following Apps and Devices
= render partial: "health_data/data_source_table"

app/views/health_data/connections.html.haml
.row
  .col-md-12
    %h3 My Data Connections
    %p By connecting different health data sources, you help researchers from around the world help understand how this condition impacts you. Fusce erat velit, luctus at tempor non, hendrerit sit amet ligula. Praesent quis eleifend magna. Proin nec nibh ut mi elementum tristique sit amet non est.
    %p Fusce erat velit, luctus at tempor non, hendrerit sit amet ligula. Praesent quis eleifend magna. Proin nec nibh ut mi elementum tristique sit amet non.



%br/


- source_num = 0

- @pprn["data_sources"].each do |source,junk|
  - if (source_num % 3 == 0)
    .row

  .col-md-4
    .panel.panel-default
      .panel-body
        %h4= source
        - if ![true,false,false,false].shuffle.first
          %button.btn.btn-success.btn-sm Connect
        - else
          %button.btn.btn-default.disabled.btn-sm Connected



  - source_num += 1

app/views/health_data/learn.html.haml
- if @ccfa_pprn
  %h3 Welcome to the CCFA Partners PPRN My Health Data Environment

  %p In this area you will be able to:

  %ul
    %li Record, Track and Analyze your IBD Symptoms
    %li Link and Share Information from Selected Apps and Devices



  %h3 How to participate

  %p We have identified 2 ways to share data.  Sources of data include:

  %ul
    %li Direct participation in CCFA Partners surveys (participant entered data (surveys & portal)
    %li Authorization of data to be shared from external sources

  %p Apps and devices offer a growing range of ways to get the important health information you're tracking into you’re My Health Data record. Many apps let you analyze and manage that information to help you achieve your health goals.

  %p Connected apps and devices are websites, software programs, and mobile apps that can help you get more out of—and put more into My Health Data.

  %p My Health Data lets you integrate data from apps and devices with your survey data, to track your health, manage your goals, and simultaneously contribute to research.
- else
  %p Duis ultricies suscipit nibh viverra rhoncus. Nulla viverra est justo, vitae lobortis lacus imperdiet non. Phasellus sed lectus a nibh vulputate aliquet eu quis mauris. Donec ultrices sollicitudin nunc, sit amet congue elit. Pellentesque sollicitudin, nisl a dignissim lobortis, ligula sem laoreet nunc, quis molestie leo est eu risus. Proin metus arcu, aliquam eu interdum sed, volutpat mattis diam.

  %p Pellentesque posuere quis metus nec molestie. Vestibulum ut iaculis leo, feugiat condimentum nibh. Ut urna augue, dapibus at vestibulum sed, suscipit at tortor. Nunc eget dignissim metus. Proin lobortis magna ut nibh blandit, non sodales augue mollis. Morbi quis pellentesque dolor. Nam suscipit in nisl at mollis.

  %p Nullam tincidunt ornare volutpat. In quis orci felis. Donec euismod dui sed lacus facilisis luctus. Suspendisse imperdiet nunc pulvinar dictum laoreet. Ut sit amet velit sodales, tincidunt massa et, cursus est. Ut adipiscing viverra turpis. Vivamus dapibus turpis et viverra hendrerit. Nunc mattis tincidunt risus, a porttitor urna sodales vel. Praesent egestas libero bibendum malesuada tincidunt.

%br/
.panel.panel-default
  .panel-heading
    %h4.panel-title Available Apps
  = render partial: "data_source_table"

%a.btn.btn-primary{:href => data_connections_path} Connect These Apps

app/views/health_data/medications.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title My Medications

  %table.table.table-striped.table-responsive

    %tbody
      - ["Cipro","6MP","Prednisone"].each do |med|
        %tr
          %td= med

  .panel-footer
    .text-center
      .btn.btn-default Update

app/views/health_data/my_dashboard.html.haml
- @title = "My Dashboard"
- @active_sub_nav = :my_dashboard


Dashboard goes here.
%br/

.panel.panel-default
  .panel-heading
    %h3.panel-title My Medications

  - if @med_list.empty?
    .panel-body
      .alert.alert-info We currently have no medication information on you.
  - elsif @med_list['meds'].any?
    %table.table
      %tbody
        - @med_list['meds'].each do |med|
          %tr
            %td= med


  .panel-footer
    %em.pull-left= "Current as of #{@med_list['date']}" if @med_list['date']
    - if current_user
      %a.btn.btn-success.pull-right{href: (current_user.get_med_update_url if OODT_ENABLED)} Update my Meds
    .clearfix

app/views/health_data/my_health_measures.html.haml
- @title = "My Health Measures"
- @active_sub_nav = :my_health_measures


- if current_user && OODT_ENABLED
  %h3 My Health Measures
  %hr/

  .row
  - @chart_urls.each do |chart_name, chart_url|
    .col-md-12.text-center
      //.col-md-6 #.col-md-12.col-sm-6
      //%h4= chart_name.titleize
      = image_tag( chart_url, alt: "#{chart_name} Chart", title: "#{chart_name} Chart")
      %hr/



    -## • cdaActivityChart
    -## • myAnxietySymptoms
    -## • myDepressionSymptoms
    -## • myFatigueSymptoms
    -## • myPainSymptoms
    -## • myQoL
    -## • mySleepDisturbance
    -## • mySocialRelations


-# Old Progress Bars

-#- if current_user && OODT_ENABLED
-#  %h3 My Reports
-#  %hr/

-#  - current_user.health_attribute_data.each do |attribute|
-#    %h4= attribute[:title]
-#    / = render :partial => "shared/progress", locals: {attribute: attribute}

-#    .progress
-#      - attribute[:zones].each do |zone|
-#        .progress-bar.progress-bar-success{style: "width: #{zone[:endValue] / 10}%"}
-#          %span= zone[:title]



-#      /{element: 1, title: "Blood Type", value: 500, zones: [{startValue: 1, endValue: 888, title: "Low"}, {startValue: 300, endValue: 999, title: "High"}], markers: [{value: 1, title: "User Max"}, {value: 2, title: "User Average"}] },


-#    %hr/

app/views/health_data/reports.html.haml
%h3 My Reports
%hr/

- current_user.health_attribute_data.each do |attribute|
  %h4= attribute[:title]
  / = render :partial => "shared/progress", locals: {attribute: attribute}

  .progress
    - attribute[:zones].each do |zone|
      .progress-bar.progress-bar-success{style: "width: #{zone[:endValue] / 10}%"}
        %span= zone[:title]



    /{element: 1, title: "Blood Type", value: 500, zones: [{startValue: 1, endValue: 888, title: "Low"}, {startValue: 300, endValue: 999, title: "High"}], markers: [{value: 1, title: "User Max"}, {value: 2, title: "User Average"}] },


  %hr/

app/views/health_data/surveys.html.haml
/ - questions = {"How would you describe your general well-being over the last week?" => ["Generally Well", "Slightly below Par", "Poor", "Very Poor", "Terrible"], "On average, over the past week, would you rate your abdominal pain as..." => ["None","Mild","Moderate","Severe"], "On average, over the past week, how many liquid or very soft stools have you had per day?" => ["0","1","2","3","4-7","8-14","15+"]}

/ - questions.each do |question, answers|
/   %h4= question
/   .text-center
/     - answers.each do |answer|
/       .btn.btn-default= answer
/   %hr/




.panel.panel-default
  .panel-heading
    %h3.panel-title New Surveys
    .req surveys_ready_for_completion (title of survey, url to survey)
  .list-group
    - @incomplete_surveys.each do |survey|
      = link_to start_or_resume_survey(survey), class: 'list-group-item' do
        %h3= survey.name
        = render partial: 'surveys/partials/session_progress', locals: {stats: survey.completion_stats(current_user), question_flow: survey}
    - @unstarted_surveys.each do |survey|
      = link_to start_or_resume_survey(survey), class: 'list-group-item' do
        %h3= survey.name
        %p Survey not yet started.
        %p
          %strong
            Estimated time commitment:
            = survey.total_time.ceil
            minutes for
            = survey.all_questions.length
            questions.

          //= link_to "Complete Survey", start_or_resume_survey(survey), class: "btn btn-success btn-sm"

.panel.panel-default
  .panel-heading
    %h3.panel-title Surveys You've Completed
    .req surveys_ready_for_completion (title of survey, url to survey)
  .list-group
    - if @complete_surveys.empty?
      .list-group-item
        %span.text-info None so far!
    - @complete_surveys.each do |survey|
      .list-group-item
        %h3= survey.name
        %p
          %strong Survey finished!
        %div
          = link_to 'Review Answers', survey_report_path(answer_session_id: survey.most_recent_answer_session(current_user).id), class: 'btn btn-default btn-sm'
          = link_to 'Retake Survey', start_survey_path(question_flow_id: survey.id), class: 'btn btn-default btn-sm', data: {confirm: "Are you sure you want to retake the questionnaire?", description: "All your progress will be lost, and you'll have complete the questionnaire again."}