config/routes.rb
Rails.application.routes.draw do

  root 'static#splash'
  get 'home' => "home#index"
  get 'about' => 'static#about'
  get 'resources' => 'static#resources'

  get 'external_link_warning' => 'static#external_link_warning'
  get 'content/:page' => 'static#content'
  get 'content/' => 'static#content'

  get 'privacy_policy_document' => 'static#content', :page => "privacy_policy"
  get 'terms_of_service' => 'static#content', :page => "terms_of_service"

  match 'research_topics_tab', to: "research_topics#research_topics", via: :get, as: :research_topics_ajax
  get 'vote_counter' => 'research_topics#vote_counter'
  match 'comment_on_research_topic', to: "research_topics#comment", via: [:post], as: :comment_on_research_topic
  resources :research_topics

  get 'research_surveys' => 'research#research_surveys', as: :surveys

  get 'research' => 'research#index'
  get 'research_prioritization' => 'research#index'
  get 'research_active_studies' => 'research#active_studies'
  get 'research_completed_research' => 'research#completed_research'
  get 'research_my_contributions' => 'research#my_contributions'

  get 'data_connections' => 'research#data_connections'

  get 'research_surveys/report/:answer_session_id', to: 'surveys#show_report', as: :survey_report
  get 'research_surveys/:question_flow_id', to: 'surveys#start_survey', as: :start_survey
  get 'research_surveys/:answer_session_id/:question_id', to: 'surveys#ask_question', as: :ask_question
  match 'research_surveys/process_answer', to: 'surveys#process_answer', via: :post, as: :process_answer
  get 'questions/frequencies(/:question_id/:answer_session_id)', to: "questions#frequencies", as: :question_frequencies, format: :json
  get 'questions/typeahead/:question_id', to: "questions#typeahead", as: :question_typeahead, format: :json

  get 'health_data' => 'health_data#index'
  get 'health_data/my_trends' => 'health_data#index', as: :my_trends
  get 'health_data/my_health_measures' => 'health_data#my_health_measures', as: :my_health_measures
  get 'health_data/my_dashboard' =>  'health_data#my_dashboard', as: :my_dashboard
  get 'health_data/my_connections' =>  'health_data#my_connections', as: :my_connections

  get 'data_reports' => 'health_data#reports'
  get 'data_medications' => 'health_data#medications'
  get 'data_intro' => 'health_data#intro'
  match 'check_in', to: "health_data#check_in", via: :post, as: :check_in

  match 'members', to: 'members#index', via: :get, as: 'members' # show
  match 'members/profile', to: 'members#profile', as: 'social_profile', via: :get #edit
  match 'members/profile', to: 'members#update_profile', as: 'update_social_profile', via: [:put, :post, :patch] # update
  match 'locations', via: :get, as: :locations, format: :json, to: 'members#locations'

  get 'blog' => 'blog#blog'
  get 'blog_findings' => 'blog#blog_findings'

  get 'account' => 'account#account'
  get 'account_export' => 'account#account_export'
  match 'consent', to: "account#consent", as: :consent, via: [:get, :post]
  match 'privacy_policy', to: "account#privacy_policy", as: :privacy, via: [:get, :post]
  match 'update_account', to: 'account#update', as: 'update_account', via: :patch
  match 'change_password', to: 'account#change_password', as: 'change_password', via: :patch

  match 'members/discussion/terms_and_conditions', to: 'account#terms_and_conditions', via: :get, as: :terms_and_conditions

  get 'admin' => 'admin#users'
  match 'admin/users', to: 'admin#users', as: 'admin_users', via: [:get, :post]
  get 'admin/surveys' => 'admin#surveys', as: 'admin_surveys'
  get 'admin/blog' => 'admin#blog', as: 'admin_blog'
  get 'admin/notifications' => 'admin#notifications', as: 'admin_notifications'
  get 'admin/research_topics' => 'admin#research_topics', as: 'admin_research_topics'
  get 'admin/research_topic/:id' => 'admin#research_topic', as: 'admin_research_topic'

  match 'add_role', to: "admin#add_role_to_user", via: :post, as: :add_role, format: :js
  match 'remove_role', to: "admin#remove_role_from_user", via: :post, as: :remove_role, format: :js
  match 'destroy_user', to: "admin#destroy_user", via: :post, as: :destroy_user, format: :js

  get 'pprn' => 'application#toggle_pprn_cookie'

  resources :questions
  match 'vote', to: 'votes#vote', via: :post, as: :vote
  match 'vote', to: 'research_topics#index', via: :get, as: :vote_fake

  resources :posts, except: [:show, :index]

  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions'}

  devise_scope :user do
    get 'pairing_wizard' => 'registrations#pairing_wizard'
    post 'pairing_wizard' => 'registrations#pairing_wizard' #enables trying specified email
    get 'redirect_to_lcp_reg' => 'registrations#redirect_to_lcp_reg'
  end

  mount Forem::Engine, :at => '/members/discussion'

end

app/views/admin/admin_blog.html.haml
%h3 Blog Posts
= render :partial => "shared/blog_posts", :locals => { :editable => true }

app/views/admin/admin_notifications.html.haml
%h3 Notifications
= render :partial => "shared/notifications", :locals => { :editable => true }

app/views/admin/admin_research_topics.html.haml
%h3 Research Topics
= render :partial => "shared/research_topics", :locals => { :editable => true, :star_pattern => :popular, :num_loops => 5}

app/views/admin/admin_surveys.html.haml
%h3 Surveys

.panel.panel-default
  .panel-heading
    %h3.panel-title Questions
  .panel-body
    = render partial: "questions/list"
    = link_to "+ Add New Question"

.panel.panel-default
  .panel-heading
    %h3.panel-title Surveys
  .panel-body
    = render partial: "surveys/partials/list"
    = link_to "+ Create New Survey"

app/views/admin/admin_users.html.haml
%h3 User Management

.panel.panel-default
  .panel-heading
    .btn-toolbar{role: "toolbar"}
      .btn-group
        %button.btn.btn-default{type: "button"} All Users
        %button.btn.btn-default{type: "button"} Admins
        %button.btn.btn-default{type: "button"} Owners

      .btn-group.col-md-4
        %form#user-search.form-inline{ role: 'form', action: admin_path, :style => "display: inline;" }
          %input{name: 'authenticity_token', type: "hidden", value: form_authenticity_token}
          %label.control-label.sr-only Limit by user email
          .input-group
            %input.form-control{type: 'search', placeholder: 'Search by Email', name: 'search', value: params[:search]}
            %span.input-group-btn
              %button.btn.btn-default{type: "submit", value: ""} Search



  .table-responsive
    %table.table
      %thead
        %tr
          %th
            User
          %th
            Role

      %tbody
        - @users.each do |user|
          %tr.user{data: {user_id: user.id}}
            %td= user.email
            %td
              - user.roles.each do |role|
                %span.label.label-default{:style => "margin-right: 5px;"}
                  = role.name.capitalize
                  %a.remove-role{data: {role: role.name}, :style => "color: inherit;"}
                    %i.fa.fa-times

              / Single button
              .btn-group.pull-right
                %button.btn.btn-primary.btn-xs.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
                  Action
                  %span.caret
                %ul.dropdown-menu{role: "menu"}
                  %li
                    %a{href: "#"} Make Admin
                  %li
                    %a{href: "#"} Make Owner
                  %li.divider
                  %li
                    %a{href: "#"} Delete User

                  -# Roles
                  -# %select#role.form-control.pull-right.input-sm{data: {add_target: add_role_path, remove_target: remove_role_path, authenticity_token: form_authenticity_token}}
                  -#   %option.input-sm{value: "admin"} admin
                  -#   %option.input-sm{value: "owner"} owner
                  -#   %button.add-role.btn.btn-primary.btn-xs.pull-right{type: "button"}
                  -#     %i.fa.fa-plus
                  -#     Add

app/views/admin/blog.html.haml
%h3 Blog Posts
= render partial: "shared/blog_posts", locals: { blog_posts: @posts, new_blog_post: @new_post, short: false }

app/views/admin/notifications.html.haml
%h3 Notifications
= render partial: "shared/notifications", locals: { notifications: @posts, new_notification: @new_post }

app/views/admin/research_topic.html.haml
%h3 Moderate Reseach Topic
= render partial: 'research_topics/form', locals: {research_topic: @research_topic}

%br

= render partial: "research_topics/research_topic_discussion", locals: {research_topic: @research_topic}

app/views/admin/research_topics.html.haml
.panel.panel-default.research_topics
  .panel-heading
    %h3 Research Topics
  %table.table.table-responsive.table-striped
    %thead
      %tr
        %th Rating
        %th Text
        %th User
        %th State
        %th Submitted At
        %th Options
    %tbody
      - @research_topics.each do |research_topic|
        %tr
          %td= research_topic.rating
          %td= research_topic.text
          %td= research_topic.user
          %td= research_topic.state
          %td= research_topic.created_at.strftime("%d-%m-%Y %H:%M")
          %td
            .btn-group
              = link_to "Moderate", admin_research_topic_path(research_topic), class: "btn btn-success btn-xs"
              = link_to "Delete", research_topic_path(research_topic, method: :delete), class: "btn btn-danger btn-xs"

app/views/admin/surveys.html.haml
%h3 Surveys

.panel.panel-default
  .panel-heading
    %h3.panel-title Questions
  .panel-body
    = render partial: "questions/list"
    = link_to "+ Add New Question"

.panel.panel-default
  .panel-heading
    %h3.panel-title Surveys
  .panel-body
    = render partial: "surveys/partials/list"
    = link_to "+ Create New Survey"

app/views/admin/update_users.js.erb
$("#admin-content").html('<%= j render file: "admin/users" %>');

app/views/admin/user_role.js.erb
$("#users").html('<%= j render partial: "admin/partials/users", locals: {users: @users} %>');

app/views/admin/users.html.haml
%h3 User Management

.panel.panel-default#admin-dashboard
  .panel-heading
    .btn-toolbar{role: "toolbar"}
      %form#user-search.form-inline{ role: 'form', action: admin_users_path, :style => "display: inline;" }

        .col-sm-5
          .btn-group.btn-group-sm{data: {toggle: 'buttons'}}
            %label.btn.btn-default
              %input{type: 'radio', name: 'search_role', value: ''} All Users
            %label.btn.btn-default
              %input{type: 'radio', name: 'search_role', value: 'admin'} Admins
            %label.btn.btn-default
              %input{type: 'radio', name: 'search_role', value: 'owner'} Owners
            %label.btn.btn-default
              %input{type: 'radio', name: 'search_role', value: 'moderator'} Moderators
        .col-sm-7
          .btn-group
            %input#auth-token{name: 'authenticity_token', type: "hidden", value: form_authenticity_token}
            %label.control-label.sr-only Limit by user email
            .input-group
              %input.form-control{type: 'search', placeholder: 'Search by Email', name: 'search', value: params[:search]}
              %span.input-group-btn
                %button.btn.btn-default{type: "submit", value: ""} Search



  .table-responsive
    %table.table#role{data: {add_target: add_role_path, remove_target: remove_role_path, destroy_target: destroy_user_path}}
      %thead
        %tr
          %th
            User
          %th
            Role

      %tbody
        - @users.each do |user|
          %tr.user{data: {user_id: user.id}}
            %td= user.email
            %td
              - user.roles.each do |role|
                %span.label.label-default{:style => "margin-right: 5px;"}
                  = role.name.titleize
                  %a.remove-role{data: {role: role.name}, :style => "color: inherit;"}
                    %i.fa.fa-times

              / Single button
              .btn-group.pull-right
                %button.btn.btn-primary.btn-xs.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
                  Action
                  %span.caret
                %ul.dropdown-menu{role: "menu"}
                  %li
                    %a.add-role{href: "#", data: {role: 'admin'}} Make Admin
                  %li
                    %a.add-role{href: "#", data: {role: 'owner'}} Make Owner
                  %li
                    %a.add-role{href: "#", data: {role: 'moderator'}} Make Moderator
                  %li.divider
                  %li
                    %a.add-role{href: "#", data: {role: 'research_team'}} Add to Research Team
                  %li
                    %a.add-role{href: "#", data: {role: 'patient_team'}} Add to Patient Team
                  %li
                    %a.add-role{href: "#", data: {role: 'tech_team'}} Add to Tech Team
                  %li
                    %a.add-role{href: "#", data: {role: 'help_center'}} Add to Help-Center Team
                  %li.divider
                  %li
                    %a.delete-user{href: "#"} Delete User