config/routes.rb
Rails.application.routes.draw do

  root 'static#splash'
  get 'home' => "home#index"
  get 'about' => 'static#about'
  get 'resources' => 'static#resources'

  get 'external_link_warning' => 'static#external_link_warning'
  get 'content/:page' => 'static#content'
  get 'content/' => 'static#content'

  get 'privacy_policy_document' => 'static#content', :page => "privacy_policy"
  get 'terms_of_service' => 'static#content', :page => "terms_of_service"

  match 'research_topics_tab', to: "research_topics#research_topics", via: :get, as: :research_topics_ajax
  get 'vote_counter' => 'research_topics#vote_counter'
  match 'comment_on_research_topic', to: "research_topics#comment", via: [:post], as: :comment_on_research_topic
  resources :research_topics

  get 'research_surveys' => 'research#research_surveys', as: :surveys

  get 'research' => 'research#index'
  get 'research_prioritization' => 'research#index'
  get 'research_active_studies' => 'research#active_studies'
  get 'research_completed_research' => 'research#completed_research'
  get 'research_my_contributions' => 'research#my_contributions'

  get 'data_connections' => 'research#data_connections'

  get 'research_surveys/report/:answer_session_id', to: 'surveys#show_report', as: :survey_report
  get 'research_surveys/:question_flow_id', to: 'surveys#start_survey', as: :start_survey
  get 'research_surveys/:answer_session_id/:question_id', to: 'surveys#ask_question', as: :ask_question
  match 'research_surveys/process_answer', to: 'surveys#process_answer', via: :post, as: :process_answer
  get 'questions/frequencies(/:question_id/:answer_session_id)', to: "questions#frequencies", as: :question_frequencies, format: :json
  get 'questions/typeahead/:question_id', to: "questions#typeahead", as: :question_typeahead, format: :json

  get 'health_data' => 'health_data#index'
  get 'health_data/my_trends' => 'health_data#index', as: :my_trends
  get 'health_data/my_health_measures' => 'health_data#my_health_measures', as: :my_health_measures
  get 'health_data/my_dashboard' =>  'health_data#my_dashboard', as: :my_dashboard
  get 'health_data/my_connections' =>  'health_data#my_connections', as: :my_connections

  get 'data_reports' => 'health_data#reports'
  get 'data_medications' => 'health_data#medications'
  get 'data_intro' => 'health_data#intro'
  match 'check_in', to: "health_data#check_in", via: :post, as: :check_in

  match 'members', to: 'members#index', via: :get, as: 'members' # show
  match 'members/profile', to: 'members#profile', as: 'social_profile', via: :get #edit
  match 'members/profile', to: 'members#update_profile', as: 'update_social_profile', via: [:put, :post, :patch] # update
  match 'locations', via: :get, as: :locations, format: :json, to: 'members#locations'

  get 'blog' => 'blog#blog'
  get 'blog_findings' => 'blog#blog_findings'

  get 'account' => 'account#account'
  get 'account_export' => 'account#account_export'
  match 'consent', to: "account#consent", as: :consent, via: [:get, :post]
  match 'privacy_policy', to: "account#privacy_policy", as: :privacy, via: [:get, :post]
  match 'update_account', to: 'account#update', as: 'update_account', via: :patch
  match 'change_password', to: 'account#change_password', as: 'change_password', via: :patch

  match 'members/discussion/terms_and_conditions', to: 'account#terms_and_conditions', via: :get, as: :terms_and_conditions

  get 'admin' => 'admin#users'
  match 'admin/users', to: 'admin#users', as: 'admin_users', via: [:get, :post]
  get 'admin/surveys' => 'admin#surveys', as: 'admin_surveys'
  get 'admin/blog' => 'admin#blog', as: 'admin_blog'
  get 'admin/notifications' => 'admin#notifications', as: 'admin_notifications'
  get 'admin/research_topics' => 'admin#research_topics', as: 'admin_research_topics'
  get 'admin/research_topic/:id' => 'admin#research_topic', as: 'admin_research_topic'

  match 'add_role', to: "admin#add_role_to_user", via: :post, as: :add_role, format: :js
  match 'remove_role', to: "admin#remove_role_from_user", via: :post, as: :remove_role, format: :js
  match 'destroy_user', to: "admin#destroy_user", via: :post, as: :destroy_user, format: :js

  get 'pprn' => 'application#toggle_pprn_cookie'

  resources :questions
  match 'vote', to: 'votes#vote', via: :post, as: :vote
  match 'vote', to: 'research_topics#index', via: :get, as: :vote_fake

  resources :posts, except: [:show, :index]

  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions'}

  devise_scope :user do
    get 'pairing_wizard' => 'registrations#pairing_wizard'
    post 'pairing_wizard' => 'registrations#pairing_wizard' #enables trying specified email
    get 'redirect_to_lcp_reg' => 'registrations#redirect_to_lcp_reg'
  end

  mount Forem::Engine, :at => '/members/discussion'

end

app/models/surveys/answer.rb
class Answer < ActiveRecord::Base
  has_many :answer_values, dependent: :destroy
  belongs_to :question
  belongs_to :answer_option
  belongs_to :answer_session
  has_one :in_edge, class_name: "AnswerEdge", foreign_key: "child_answer_id", dependent: :destroy
  has_one :out_edge, class_name: "AnswerEdge", foreign_key: "parent_answer_id", dependent: :destroy
  belongs_to :user # When necessary

  def self.first_answer(question, answer_session)
    Answer.where(question_id: question.id, answer_session_id: answer_session.id).first
  end

  ## Different options:
  # It gets complicated with many answer templates
  #   at most basic, one answer template with not allowed multiple ==> target field gets value
  #   then, one answer templates with allowed multiple ==> builds from array of values
  #
  #   we repeat this for all answer templates
  #
  #   the inputs can be single value, array of values, hash with answer templates as keys
  #   if multiple answer templates are present, then hash is NECESSARY

  # single value, raw value!
  # single value, answer option id (multiple_choice)
  # Multiple Values, answer option id (check_box)
  # (not supported now) multiple values,

  def value=(val)
    answer_values.clear

    question.answer_templates.each do |template|
      target_field = template.data_type

      if val.kind_of?(Hash)
        val_for_template = val[template.id.to_s]
      else
        val_for_template = val
      end

      if template.allow_multiple and val_for_template.kind_of?(Array)
        val_for_template.each {|v| answer_values.build(target_field => v, 'answer_template_id' => template.id) }
      else
        answer_values.build(target_field => val_for_template, 'answer_template_id' => template.id)
      end
    end

    if self.persisted?
      self.save
    end
  end

  def value
    res = {}
    answer_values.each do |av|
      res[av.answer_template.id] ||= []
      res[av.answer_template.id] << av.value
    end

    res.each_pair { |k, v| res[k] = v.first if v.length == 1 }

    res

    # if question.present? and question.answer_templates.present?
    #   val_container = {}
    #
    #   question.answer_templates.each do |template|
    #     target_field = template.data_type
    #     template_answer_values = answer_values.where(answer_template_id: template.id)
    #
    #     if template.allow_multiple and template_answer_values.length > 1
    #       val_container[template.id] = template_answer_values.map{|av| av[target_field] }
    #     elsif answer_values.length == 1
    #       val_container[template.id] =  template_answer_values.first[target_field]
    #     else
    #       nil
    #     end
    #   end
    #
    #   if val_container.values.length == 1
    #     val_container.values.first
    #   else
    #     val_container
    #   end
    #
    # else
    #   nil
    # end
  end

  def string_value
    res = {}
    answer_values.each do |av|
      res[av.answer_template.id.to_s] ||= []
      res[av.answer_template.id.to_s] << av.string_value
    end

    res.each_pair { |k, v| res[k] = v.first if v.length == 1 }

    res
  end

  def show_value
    if answer_values.length == 1
      answer_values.first.show_value
    else
      answer_values.map(&:show_value).join(", ")
    end
  end

  def next_answer
    out_edge.present? ? out_edge.child_answer : nil
  end

  def previous_answer
    in_edge.present? ? in_edge.parent_answer : nil
  end

  def descendants
    descendant_list = []

    head = self.next_answer
    while head
      descendant_list << head
      head = head.next_answer
    end

    descendant_list
  end

  def destroy_descendant_edges
    descendants.each do |d|
      d.in_edge.destroy if d.in_edge
      d.out_edge.destroy if d.out_edge
    end
  end

  def next_question
    candidate_edges = QuestionEdge.where(parent_question_id: question.id, direct: true, question_flow_id: answer_session.question_flow.id)

    if candidate_edges.empty?
      nil
    else
      if candidate_edges.length == 1
        chosen_edge = candidate_edges.first
      else
        chosen_edge = candidate_edges.select {|e| self.fits_condition?(e.condition)}.first || candidate_edges.select { |e| e.condition == nil }.first || candidate_edges.first
      end
      chosen_edge.descendant
    end

  end

  def fits_condition?(condition)
    all_values = answer_values.map(&:string_value)

    all_values.include? condition
  end

  def multiple_options?
    question.links_as_parent.length > 1
  end
end

app/models/surveys/answer_edge.rb
class AnswerEdge < ActiveRecord::Base
  belongs_to :parent_answer, class_name: "Answer"
  belongs_to :child_answer, class_name: "Answer"
  belongs_to :answer_session
end

app/models/surveys/answer_option.rb
class AnswerOption < ActiveRecord::Base
  include Localizable

  has_many :answer_templates, through: :answer_options_answer_templates, join_table: :answr_options_answer_templates
  has_many :answer_values

  localize :text_value

  def value
    text_value || time_value || numeric_value
  end
end

app/models/surveys/answer_options_answer_template.rb
class AnswerOptionsAnswerTemplate < ActiveRecord::Base
  self.table_name = 'answr_options_answer_templates'

  belongs_to :answer_template
  belongs_to :answer_option
end

app/models/surveys/answer_template.rb
class AnswerTemplate < ActiveRecord::Base
  has_and_belongs_to_many :questions
  has_many :answer_options_answer_templates, -> { order "answr_options_answer_templates.created_at" }
  has_many :answer_options, through: :answer_options_answer_templates, join_table: 'answr_options_answer_templates'
  belongs_to :display_type
  belongs_to :unit




end

app/models/surveys/answer_value.rb
class AnswerValue < ActiveRecord::Base
  belongs_to :answer
  belongs_to :answer_option
  belongs_to :answer_template

  def value
    self[answer_template.data_type]
  end

  def string_value
    value.to_s
  end

  def show_value
    if answer_template.data_type == 'answer_option_id'
      answer_option.present? ? answer_option.value : nil
    else
      value
    end
  end
end

app/models/surveys/display_type.rb
class DisplayType < ActiveRecord::Base
  has_many :answer_templates

end

app/models/surveys/group.rb
class Group < ActiveRecord::Base
  has_many :questions

  def self.research_question_group
    Group.find_by_name("Research Questions")
  end

  def minimum_set(question_flow, start_point = nil)
    current_q = start_point

    # go to start of group
    if start_point.present?

      while current_q.default_previous_question(question_flow).present? and current_q.default_previous_question(question_flow).group == self
        current_q = current_q.default_previous_question(question_flow)
      end
    else
      current_q = questions.select {|q| !q.ancestors.map(&:group).include? self }.first
    end

    min_set = [current_q]

    while (current_q = current_q.default_next_question(question_flow)) and current_q.present? and current_q.group == self
      min_set << current_q

    end



    min_set
  end




end

app/models/surveys/question_edge.rb
class QuestionEdge < ActiveRecord::Base
  belongs_to :question_flow
  belongs_to :parent_question, class_name: "Question"
  belongs_to :child_question, class_name: "Question"

  include Authority::Abilities
  self.authorizer_name = "AdminAuthorizer"

  acts_as_dag_links node_class_name: 'Question', ancestor_id_column: 'parent_question_id', descendant_id_column: 'child_question_id'

  def self.build_edge(ancestor, descendant, condition = nil, qf_id = QuestionFlow.first.id)
    source = self::EndPoint.from(ancestor)
    sink = self::EndPoint.from(descendant)
    conditions = self.conditions_for(source, sink)
    conditions[:condition] = condition
    path = self.new(conditions)
    path.make_direct
    path.question_flow_id = qf_id
    path
  end




end

app/models/surveys/question_help_message.rb
class QuestionHelpMessage < ActiveRecord::Base
  include Localizable

  include Authority::Abilities
  self.authorizer_name = "AdminAuthorizer"

  has_many :questions

  localize :message

end

app/models/surveys/unit.rb
class Unit < ActiveRecord::Base
  include Localizable

  has_many :questions
  localize :name

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_active_top_nav_link_to_health_data

  layout "community"

  def start_survey
    @question_flow = QuestionFlow.find(params[:question_flow_id])
    @answer_session =  AnswerSession.find_by(user_id: current_user.id, question_flow_id: @question_flow.id)

    if @answer_session
      if params[:reset_survey]
        @answer_session.reset_answers
      else
        redirect_to surveys_path
      end
    else
      @answer_session = AnswerSession.create(user_id: current_user.id, question_flow_id: @question_flow.id)
    end


  end

  def ask_question
    @answer_session = AnswerSession.find(params[:answer_session_id])
    @question = Question.find(params[:question_id])

    if @question.part_of_group?
      @group = @question.group
      @questions = @group.minimum_set(@answer_session.question_flow)
      @answer = Answer.where(question_id: @questions.first.id, answer_session_id: @answer_session.id).first || Answer.new(question_id: @questions.first.id, answer_session_id: @answer_session.id)
    else
      @answer = Answer.where(question_id: @question.id, answer_session_id: @answer_session.id).first || Answer.new(question_id: @question.id, answer_session_id: @answer_session.id)
    end

  end

  def show_report
    @answer_session = AnswerSession.find(params[:answer_session_id])
    @question_flow = @answer_session.question_flow


  end

  def process_answer
    @questions = Question.where(id: params[:question_id])
    @answer_session = AnswerSession.find(params[:answer_session_id]) # Validate user!

    @questions.each do |question|
      @answer = @answer_session.process_answer(question, params)
    end

    if @answer_session.completed?
      redirect_to survey_report_path(@answer_session)
    else
      redirect_to ask_question_path(question_id: @answer.next_question.id, answer_session_id: @answer_session.id)
    end
  end



  private


end

app/helpers/surveys_helper.rb
module SurveysHelper
  def previous_question_path(answer)
    if answer.answer_session.first_answer.nil? or answer.answer_session.first_answer == answer
      start_survey_path(question_flow_id: answer.answer_session.question_flow.id)
    elsif answer.previous_answer.present?
      ask_question_path(question_id: answer.previous_answer.question.id, answer_session_id: answer.answer_session.id)
    else
      ask_question_path(question_id: answer.answer_session.last_answer.question.id, answer_session_id: answer.answer_session.id)
    end
  end

  def have_checked?(answer, answer_template, val)
    if answer.present? and answer.value.present? and answer.value[answer_template.id].present?
      saved_val = answer.value[answer_template.id]

      if saved_val.kind_of?(Array)
        saved_val.include? val
      else
        saved_val == val
      end
    else
      false
    end

  end

  def start_or_resume_survey(question_flow, answer_session = nil)
    if answer_session.present? and answer_session.started? and answer_session.last_answer.present? and answer_session.last_answer.next_question.present?
      ask_question_path(answer_session_id: answer_session.id, question_id: answer_session.last_answer.next_question.id)
    else
      start_survey_path(question_flow_id: question_flow.id)
    end
  end

  def next_survey?(current_qf)
    QuestionFlow.where(status: "show").select{|qf| qf.id != current_qf.id }.first.present?

  end

  def go_to_next_survey(user, current_qf)
    next_qf = QuestionFlow.where(status: "show").select{|qf| qf.id != current_qf.id }.first
    as = user.answer_sessions.where(question_flow_id: next_qf.id)

    start_or_resume_survey(next_qf, as)
  end

  def bmi(height, weight)
    (weight/height**2 * 703).round
  end

  def bmi_category(bmi)
    if bmi < 18.5
      "Underweight"
    elsif bmi < 25
      "Normal"
    elsif bmi < 30
      "Overweight"
    else
      "Obese"
    end
  end


  def conditional_tag(condition, tag, attributes, &block)
    if condition
      haml_tag :div, attributes, &block
    else
      haml_concat capture_haml(&block)
    end
  end

  def show_questions
    # show self

    # show descendants


  end
end

app/views/surveys/_intro.html.haml
This is an intro to surveys
.text-center
  = image_tag "video.png", :style => "border: 2px solid gray;"

app/views/surveys/ask_question.html.haml
#answer-session
  .panel.panel-default
    .panel-heading
      = render partial: 'surveys/partials/header', locals: {question_flow: @answer_session.question_flow}
      = render partial: 'surveys/partials/session_progress', locals: {stats: @answer_session.calculate_status_stats(@answer), answer: @answer, answer_session: @answer_session }
    = form_tag(process_answer_path, {role: "form"}) do
      = hidden_field_tag :answer_session_id, @answer_session.id
      .panel-body
        = render partial: 'surveys/partials/help_message' if @question.question_help_message.present?
        - if @group.present?
          = render partial: 'surveys/partials/question_group'
        - else
          = render partial: 'surveys/partials/question_form', locals: {question: @question, answer_session: @answer_session, answer: @answer, parent_q: nil, condition: nil}
      .panel-footer
        = link_to 'Previous Question', previous_question_path(@answer), class: 'btn btn-lg btn-default', tabindex: -1
        %button.btn.btn-primary.btn-lg.pull-right{:name => "direction", :type => "submit", :value => "next"} Next Question

app/views/surveys/index.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title New Surveys
    .req surveys_ready_for_completion (title of survey, url to survey)
  .list-group
    - @incomplete_surveys.each do |survey|
      = link_to start_or_resume_survey(survey), class: 'list-group-item' do
        %h3= survey.name
        = render partial: 'surveys/partials/session_progress', locals: {stats: survey.completion_stats(current_user), question_flow: survey}
    - @unstarted_surveys.each do |survey|
      = link_to start_or_resume_survey(survey), class: 'list-group-item' do
        %h3= survey.name
        %p Survey not yet started.
        %p
          %strong
            Estimated time commitment:
            = survey.total_time.ceil
            minutes for
            = survey.all_questions.length
            questions.

          //= link_to "Complete Survey", start_or_resume_survey(survey), class: "btn btn-success btn-sm"

.panel.panel-default
  .panel-heading
    %h3.panel-title Surveys You've Completed
    .req surveys_ready_for_completion (title of survey, url to survey)
  .list-group
    - if @complete_surveys.empty?
      .list-group-item
        %span.text-info None so far!
    - @complete_surveys.each do |survey|
      .list-group-item
        %h3= survey.name
        %p
          %strong Survey finished!
        %div
          = link_to 'Review Answers', finished_answer_session_path(answer_session_id: as.id), class: 'btn btn-default btn-sm'
          = link_to 'Retake Questionnaire', start_answer_session_path(question_flow_id: qf.id), class: 'btn btn-default btn-sm', data: {confirm: "Are you sure you want to retake the questionnaire?", description: "All your progress will be lost, and you'll have complete the questionnaire again."}

app/views/surveys/show_report.html.haml
- # Load data using json |
- # Generate Chart       |

#review.panel-default.panel
  .panel-heading
    %h2
      Thank you for completing the
      %strong= @question_flow.name
      Survey!
  .panel-body
    .list-group
      .alert.alert-info
        Improved feedback for this survey is coming soon. Help us build feedback you'd like to see with
        %a.u-voice your suggestions!
    = render partial: "surveys/reports/report_#{@question_flow.id}" rescue nil

    = render partial: "surveys/reports/default"

app/views/surveys/start_survey.html.haml
#answer-session
  .panel.panel-default
    .panel-heading
      = render partial: 'surveys/partials/header', locals: { question_flow: @question_flow }
      = render partial: 'surveys/partials/session_progress', locals: { stats: @answer_session.calculate_status_stats, answer: nil }
    .panel-body
      %p
        = markdown @question_flow.description
    .panel-footer
      %div
        = link_to "Lets Start!", ask_question_path(answer_session_id: @answer_session.id, question_id: @question_flow.first_question.id), class: 'btn btn-primary btn-lg'

app/views/surveys/survey.html.haml
- title("Survey")

.row
  .col-md-9
    .panel.panel-default
      .panel-heading
        %h4.panel-title Question 1
      .panel-body
        %form.form-horizontal{role: "form"}
          .form-group
            %label.col-sm-4.control-label City of Diagnosis
            .col-sm-8
              %p.form-control


    .panel.panel-default
      .panel-heading
        %h4.panel-title Question 2
      .panel-body
        %form.form-horizontal{role: "form"}
          %strong Have you ever done this?
          .radio
            %label
              %input#optionsRadios1{checked: "checked", name: "optionsRadios", type: "radio", value: "option1"}/
              Yes
          .radio
            %label
              %input#optionsRadios2{name: "optionsRadios", type: "radio", value: "option2"}/
              No

    %a.btn.btn-primary.pull-right{:href => "javascript:history.back()"} Done