config/routes.rb
Rails.application.routes.draw do

  root 'static#splash'
  get 'home' => "home#index"
  get 'about' => 'static#about'
  get 'resources' => 'static#resources'

  get 'external_link_warning' => 'static#external_link_warning'
  get 'content/:page' => 'static#content'
  get 'content/' => 'static#content'

  get 'privacy_policy_document' => 'static#content', :page => "privacy_policy"
  get 'terms_of_service' => 'static#content', :page => "terms_of_service"

  match 'research_topics_tab', to: "research_topics#research_topics", via: :get, as: :research_topics_ajax
  get 'vote_counter' => 'research_topics#vote_counter'
  match 'comment_on_research_topic', to: "research_topics#comment", via: [:post], as: :comment_on_research_topic
  resources :research_topics

  get 'research_surveys' => 'research#research_surveys', as: :surveys

  get 'research' => 'research#index'
  get 'research_prioritization' => 'research#index'
  get 'research_active_studies' => 'research#active_studies'
  get 'research_completed_research' => 'research#completed_research'
  get 'research_my_contributions' => 'research#my_contributions'

  get 'data_connections' => 'research#data_connections'

  get 'research_surveys/report/:answer_session_id', to: 'surveys#show_report', as: :survey_report
  get 'research_surveys/:question_flow_id', to: 'surveys#start_survey', as: :start_survey
  get 'research_surveys/:answer_session_id/:question_id', to: 'surveys#ask_question', as: :ask_question
  match 'research_surveys/process_answer', to: 'surveys#process_answer', via: :post, as: :process_answer
  get 'questions/frequencies(/:question_id/:answer_session_id)', to: "questions#frequencies", as: :question_frequencies, format: :json
  get 'questions/typeahead/:question_id', to: "questions#typeahead", as: :question_typeahead, format: :json

  get 'health_data' => 'health_data#index'
  get 'health_data/my_trends' => 'health_data#index', as: :my_trends
  get 'health_data/my_health_measures' => 'health_data#my_health_measures', as: :my_health_measures
  get 'health_data/my_dashboard' =>  'health_data#my_dashboard', as: :my_dashboard
  get 'health_data/my_connections' =>  'health_data#my_connections', as: :my_connections

  get 'data_reports' => 'health_data#reports'
  get 'data_medications' => 'health_data#medications'
  get 'data_intro' => 'health_data#intro'
  match 'check_in', to: "health_data#check_in", via: :post, as: :check_in

  match 'members', to: 'members#index', via: :get, as: 'members' # show
  match 'members/profile', to: 'members#profile', as: 'social_profile', via: :get #edit
  match 'members/profile', to: 'members#update_profile', as: 'update_social_profile', via: [:put, :post, :patch] # update
  match 'locations', via: :get, as: :locations, format: :json, to: 'members#locations'

  get 'blog' => 'blog#blog'
  get 'blog_findings' => 'blog#blog_findings'

  get 'account' => 'account#account'
  get 'account_export' => 'account#account_export'
  match 'consent', to: "account#consent", as: :consent, via: [:get, :post]
  match 'privacy_policy', to: "account#privacy_policy", as: :privacy, via: [:get, :post]
  match 'update_account', to: 'account#update', as: 'update_account', via: :patch
  match 'change_password', to: 'account#change_password', as: 'change_password', via: :patch

  match 'members/discussion/terms_and_conditions', to: 'account#terms_and_conditions', via: :get, as: :terms_and_conditions

  get 'admin' => 'admin#users'
  match 'admin/users', to: 'admin#users', as: 'admin_users', via: [:get, :post]
  get 'admin/surveys' => 'admin#surveys', as: 'admin_surveys'
  get 'admin/blog' => 'admin#blog', as: 'admin_blog'
  get 'admin/notifications' => 'admin#notifications', as: 'admin_notifications'
  get 'admin/research_topics' => 'admin#research_topics', as: 'admin_research_topics'
  get 'admin/research_topic/:id' => 'admin#research_topic', as: 'admin_research_topic'

  match 'add_role', to: "admin#add_role_to_user", via: :post, as: :add_role, format: :js
  match 'remove_role', to: "admin#remove_role_from_user", via: :post, as: :remove_role, format: :js
  match 'destroy_user', to: "admin#destroy_user", via: :post, as: :destroy_user, format: :js

  get 'pprn' => 'application#toggle_pprn_cookie'

  resources :questions
  match 'vote', to: 'votes#vote', via: :post, as: :vote
  match 'vote', to: 'research_topics#index', via: :get, as: :vote_fake

  resources :posts, except: [:show, :index]

  devise_for :user, controllers: { registrations: 'registrations', sessions: 'sessions'}

  devise_scope :user do
    get 'pairing_wizard' => 'registrations#pairing_wizard'
    post 'pairing_wizard' => 'registrations#pairing_wizard' #enables trying specified email
    get 'redirect_to_lcp_reg' => 'registrations#redirect_to_lcp_reg'
  end

  mount Forem::Engine, :at => '/members/discussion'

end

app/views/layouts/navigation/_account_nav.html.haml
.list-group
  %a.list-group-item{href: account_path, class: "#{"active" if action_name == "account"}"} My Settings
  %a.list-group-item{href: account_export_path, class: "#{"active" if action_name == "account_export"}"} Export Account

-# Description of this section
%p.small Your account settings page enables you to control general settings on how you are involved in the site.

%p.small
  = link_to "To update your social profile, click here.", social_profile_path

app/views/layouts/navigation/_admin_nav.html.haml
.list-group
  %a.list-group-item{href: main_app.admin_users_path, class: "#{"active" if action_name == "users"}"} Users
  %a.list-group-item{href: main_app.admin_blog_path, class: "#{"active" if action_name == "blog"}"} Blog Posts
  %a.list-group-item{href: main_app.admin_surveys_path, class: "#{"active" if action_name == "surveys"}"} Surveys
  %a.list-group-item{href: main_app.admin_research_topics_path, class: "#{"active" if /research_topic/ =~ action_name }"} Research Topics


  -#%a.list-group-item{href: forem.admin_root_path, class: "#{ 'active' if controller_path =~ /forem/ }"} Forums
  -#%a.list-group-item{href: main_app.admin_notifications_path, class: "#{"active" if action_name == "notifications"}"} Notifications


.list-group
  %a.list-group-item.list-group-item-warning{href: "https://openpprn.uservoice.com/admin", :target => "_blank"} UserVoice
  %a.list-group-item.list-group-item-warning{href: "https://www.google.com/analytics/web/?hl=en#report/visitors-overview/a53742602w86512802p89760206/", :target => "_blank"} Google Analytics



-# Description of this section
%p.small This admin panel gives admins control over content and publishings on the site.

app/views/layouts/navigation/_content_nav.html.haml
.list-group
  %a.list-group-item{href: content_path(page: "about_partners"), class: "#{"active" if @page == "about_partners"}"}
    About Partners
  -# %a.list-group-item{href: content_path(page: "about_kids_and_teens"), class: "#{"active" if @page == "about_kids_and_teens"}"}
  -#   About Kids and Teens
  %a.list-group-item{href: content_path(page: "about_ccfa"), class: "#{"active" if @page == "about_ccfa"}"}
    About CCFA
  %a.list-group-item{href: content_path(page: "research_team"), class: "#{"active" if @page == "research_team"}"}
    Research Team
  %a.list-group-item{href: content_path(page: "results"), class: "#{"active" if @page == "results"}"}
    Results
  %a.list-group-item{href: content_path(page: "faq"), class: "#{"active" if @page == "faq"}"}
    FAQ

%br/

%h4 More CCFA Resources

.list-group.small
  %a.list-group-item{href: "http://www.ccfa.org/chapters/", :target => "_blank"}
    Chapters and Support Groups
    %i.fa.fa-external-link.pull-right
  %a.list-group-item{href: "http://www.ccfacommunity.org/"}
    Community Website
    %i.fa.fa-external-link.pull-right
  %a.list-group-item{href: "http://www.ccfa.org/living-with-crohns-colitis/talk-to-a-specialist/"}
    IBD Help Center
    %i.fa.fa-external-link.pull-right
  %a.list-group-item{href: "http://www.ccfa.org/what-are-crohns-and-colitis/"}
    Disease Information
    %i.fa.fa-external-link.pull-right
  %a.list-group-item{href: "http://www.ccfacommunity.org/ChatSeries.aspx"}
    Online Support Groups
    %i.fa.fa-external-link.pull-right
  %a.list-group-item{href: "http://www.ccfacommunity.org/ExpertQA.aspx"}
    Expert Q&A Library
    %i.fa.fa-external-link.pull-right
  %a.list-group-item{href: "http://www.ccfa.org/get-involved/be-an-advocate/"}
    Advocacy Information
    %i.fa.fa-external-link.pull-right
  %a.list-group-item{href: "http://www.ccfa.org/resources/webcasts.html"}
    Webcasts
    %i.fa.fa-external-link.pull-right

-# Description of this section

= render partial: "shared/promotion_to_join" if !current_user

app/views/layouts/navigation/_top_navigation_bar.html.haml
-##############
-##### Top Navigation Bar
-##############

.row
  .col-md-12.pprn-heading

    -#### Title
    %a{href: root_path, style: "color: #222"}
      %h1.pull-left= Figaro.env.website_title


    -##############
    -##### Upper Right Small Nav
    -##############
    .pull-right
      %br/

      %ul.nav.nav-pills.small
        %li
          %a{:href => main_app.content_path(page: "about_partners")} About
        %li
          %a{:href => main_app.resources_path} Resources
        %li
          = mail_to Figaro.env.support_email, "Help"


        -##### User Account Stuff / Sign Out
        - if current_user
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              = current_user.email
              %b.caret
            %ul.dropdown-menu
              %li
                %a{href: main_app.account_path}
                  %i.fa.fa-user &nbsp; Account Settings
              - if current_user.can?(:view_admin_dashboard)
                %li
                  %a{href: main_app.admin_path, :title => "Admin Panel"}
                    %i.fa.fa-wrench &nbsp; Admin Panel
          -# Sign Out
          %li
            = link_to "<i class='fa fa-sign-out'></i> Sign out".html_safe, main_app.destroy_user_session_path, :method => :delete

        - else
          -##############
          -##### Sign Up / Sign In
          -##############
          %li
            %a{:href => main_app.new_user_session_path}
              %i.fa.fa-sign-in
                Sign In / Up

    .clearfix
    %hr



-##############
-##### Major Top Nav Links
-##############

.row
  .col-md-12.pprn-nav
    %ul.nav.nav-pills.top-nav
      %li{:class => "#{"active" if @active_top_nav_link == :home}"}
        %a{href: main_app.home_path} Home
      %li{:class => "#{"active" if @active_top_nav_link == :research}"}
        %a{href: main_app.research_path} Research
      %li{:class => "#{"active" if @active_top_nav_link == :health_data}"}
        %a{href: main_app.health_data_path} My Health Data
      %li{class: "#{"active" if @active_top_nav_link == :members}"}
        %a{href: main_app.members_path} Members